### ISSUE TITLE
[JOSS] Licensing and relationships between libraries

### ISSUE THREAD

**Issue by yongrenjie** [LTLA/libscran#59]
(This issue is opened as part of @yongrenjie and @llewelld's review of the Journal of Open Source Software submission, [*'Powering single-cell analyses in the browser with WebAssembly'*](https://github.com/openjournals/joss-reviews/issues/5603).)

---

[scran is GPLv3](https://code.bioconductor.org/browse/scran/blob/RELEASE_3_17/DESCRIPTION#L68), whereas [libscran is MIT](https://github.com/LTLA/libscran/blob/master/LICENSE). This is fine, except that in the libscran repository it states that "scran.js is heavily inspired by the scran R package and contains most of its related methods. Indeed, much of the implementation in this repository is taken directly from scran and its related R packages."

Both contain C++ source. Although we could not find code shared between the two, it would be good to confirm that this is the case (i.e. that there is no shared code), as any shared code may have implications on the permissible licenses.

(In general, regarding the relationships between libraries: there is a useful diagram in the README.md relating kana, scran.js, libscran and other libraries, but we felt some additional descriptive text would be helpful, especially explaining the relationship to libscran, scran-cli and Bioconductor scran.)

**Comment by LTLA** [comment]
Hm. That's a good question. I don't think there's any code that's directly lifted from the R package. The sharing mentioned here mostly relates to the algorithms involved, and (IANAL) that's not copyrightable. The implementations are quite different by necessity, as the underlying data representations are different ([**tatami**](https://github.com/tatami-inc) versus Bioconductor's [**DelayedArray**](https://bioconductor.org/packages/DelayedArray) block-processing mechanism) and we don't have to consider access to R-managed memory via **Rcpp**.

So yes, I think I can say that there is no shared code from the R package. Though if I'm wrong... I think I am still the copyright holder of the R package, so I think I can find it in my heart to forgive myself.

**Comment by llewelld** [comment]
Thank you; that's enough to satisfy me, as long as @yongrenjie is also happy with this.

You might want to tweak the wording in the [scran.js ReadMe](https://github.com/kanaverse/scran.js/blob/c9fa537bfd887fa1a25f2dc9a91382a1d173ae3c/README.md?plain=1#L9) which at least caused the confusion for me, but given your clarification I don't personally see this as an issue for the JOSS submission.
